# Лабораторная работа 2

# Встроенные типы объектов в Pyhon

Зарихта Матвей Дмитриевич, 17 апреля 2025

## 1. Построение иерархии встроенных типов в Python

**object (объекты)**
- numbers
- int
- float
- complex
- bool
- str
- bytes
- bytearray

**collections (коллекции)**
- list (изменяемый, упорядоченный)
- tuple (неизменяемый, упорядоченный)
- dict (изменяемый, неупорядоченный*)
- set (изменяемый, неупорядоченный)
- frozenset (неизменяемый, неупорядоченный)

**NoneType**

## 2. Проработка примеров, представленных в лекционном файле

### <u>2.2 Встроенные типы объектов, представляющих числа</u>

In [28]:
import decimal as dec
import fractions as fra
print(dec.Decimal('0.1'))
print(fra.Fraction('2/3'))

0.1
2/3


Вычисления с числами типа
decimal могут иметь лучшую точность, чем вычисления с числами типа float.

Рациональные числа ( fraction ) явно хранят числитель и
знаменатель, что позволяет избежать ряда неточностей и ограничений в
вычислениях с числами с плавающей точкой ( float , decimal ).

### <u>2.3 Встроенные типы последовательностей: str, list, tuple
</u>

In [53]:
S = 'spam'

In [55]:
S[:1] + 'l' + S[2:]

'slam'

Присваивание по индексу использовать нельзя, т.к. строки неизменяемы.

<u>ДЛЯ СПИСКА:</u>

In [61]:
list1 = ['s', 'p', 'a', 'm']
list1 = list1[:1] + ['l'] + list1[2:]
print(list1)

['s', 'l', 'a', 'm']


In [67]:
list1 = ['s', 'p', 'a', 'm']
list1[1] ='l'
print(list1)

['s', 'l', 'a', 'm']


<u>ДЛЯ КОРТЕЖА:</u>

In [70]:
tuple1 = ('s', 'p', 'a', 'm')
tuple1 = tuple1[:1] + ('l',) + tuple1[2:]

Присваивание по индексу использовать нельзя, т.к. кортежи неизменяемы.

### <u>2.4 Встроенный тип отображения: dict</u>

In [30]:
dict1 = {'names': {'fam': 'zarykhta','im1': 'matsvey','im2': 'dzmytryevich'},'age': 19,'plow': 'москоу сити арбитраж','adr': 'mog. 18-23','eladr': 'tcheburek227@gmail.com','tel': '+375259451810'}

In [38]:
print(dict1['names']['fam'])
print(dict1['names']['im1'])
print(dict1['names']['im2'])
print(dict1['age'])
print(dict1['plow'])
print(dict1['adr'])
print(dict1['eladr'])
print(dict1['tel'])

zarykhta
matsvey
dzmytryevich
19
москоу сити арбитраж
mog. 18-23
tcheburek227@gmail.com
+375259451810


т.к. порядок здесь не фиксирован, да и поиск данных лучше по ключам, чем по индексам, то словарь более осмысленный)

### <u>2.5 Встроенный тип множества: set</u>

In [42]:
str1 = 'mama ama kriminal'

In [50]:
print(''.join(set(str1)))

rain mkl


### <u>2.8. Интерфейс объекта: операции и методы</u>

In [67]:
str2 = 'aaabordage'
print(str2.count('a'),
str2.index('a'))

4 0


In [69]:
list1 = ('uga', 'buga', 'apple', 'banana', 'uga', 'uga')
print(list1.count('uga'),list1.index('buga'))

3 1


In [71]:
tuple1 = ('pasxa', 'skoro', 'kak', 'je', 'kak', 'tak')
print(tuple1.count('kak'), tuple1.index('kak'))

2 2


**=====================================**

In [186]:
str2 = '    TUT NADO napisaTb CHTOTO UMNOE, NO mne Vpadlu'
str12 = str2.strip().lower().replace(" ", "_")
print(str12)

tut_nado_napisatb_chtoto_umnoe,_no_mne_vpadlu


1) <u>strip</u>:
   - удаляет пробелы в начале и в конце строки
   - можно указать символы, который нужно удалить (strip(", "))
2) <u>lower</u>:
   - все символы строки в нижний регистр
3) <u>replace(sim1, sim2)</u>:
   - заменяет подстроки sim1 на подстроку sim2

**=====================================**

In [176]:
s1 = [12, 2, 34]
s1.append(23)
s1

[12, 2, 34, 23]

In [178]:
pasxa = [2, 212, 85]
s1.extend(pasxa)
s1

[12, 2, 34, 23, 2, 212, 85]

In [180]:
s1.insert(0, 0)
s1

[0, 12, 2, 34, 23, 2, 212, 85]

**=====================================**

In [216]:
list2 = ['ps', '1', '2232', 'etewed']

In [220]:
list2.sort(key = len)
print(list2)

['1', 'ps', '2232', 'etewed']


метод sort() сортирует последовательность по возрастанию. в данном случае список сортируется по длине, т.к. в качестве key была указана длина

**=====================================**

In [225]:
dict1 = {i: 'tapochek' for i in range(100)}

In [227]:
print(dict1)

{0: 'tapochek', 1: 'tapochek', 2: 'tapochek', 3: 'tapochek', 4: 'tapochek', 5: 'tapochek', 6: 'tapochek', 7: 'tapochek', 8: 'tapochek', 9: 'tapochek', 10: 'tapochek', 11: 'tapochek', 12: 'tapochek', 13: 'tapochek', 14: 'tapochek', 15: 'tapochek', 16: 'tapochek', 17: 'tapochek', 18: 'tapochek', 19: 'tapochek', 20: 'tapochek', 21: 'tapochek', 22: 'tapochek', 23: 'tapochek', 24: 'tapochek', 25: 'tapochek', 26: 'tapochek', 27: 'tapochek', 28: 'tapochek', 29: 'tapochek', 30: 'tapochek', 31: 'tapochek', 32: 'tapochek', 33: 'tapochek', 34: 'tapochek', 35: 'tapochek', 36: 'tapochek', 37: 'tapochek', 38: 'tapochek', 39: 'tapochek', 40: 'tapochek', 41: 'tapochek', 42: 'tapochek', 43: 'tapochek', 44: 'tapochek', 45: 'tapochek', 46: 'tapochek', 47: 'tapochek', 48: 'tapochek', 49: 'tapochek', 50: 'tapochek', 51: 'tapochek', 52: 'tapochek', 53: 'tapochek', 54: 'tapochek', 55: 'tapochek', 56: 'tapochek', 57: 'tapochek', 58: 'tapochek', 59: 'tapochek', 60: 'tapochek', 61: 'tapochek', 62: 'tapochek', 6

### <u>2.9 Переменная</u>

In [234]:
list23 = [1,2,3]
list23.append(list23)
print(list23) 

[1, 2, 3, [...]]


In [242]:
dict2 = {'a': 'b'}
dict2['c'] = dict2 
print(dict2) 

{'a': 'b', 'c': {...}}


**=====================================**

In [252]:
a = b = c = d = [42]
import sys
sys.getrefcount(a)

5

также учитывается временная ссылка от getrefcount()

**=====================================**

In [261]:
orig = [1, 2, 3]
copy1 = orig.copy() 
copy2 = orig[:]   
copy3 = list(orig)
print(copy1, copy2, copy3) 

[1, 2, 3] [1, 2, 3] [1, 2, 3]


### <u>2.10 Выражение спискового включения
</u>

In [265]:
num = {1, 2, 3, 4, 5, 6, 7, 8, 9, 10}
newnum = {x + 2 for x in num if x % 2 == 0}
print(newnum)

{4, 6, 8, 10, 12}


**=====================================**

In [269]:
matrix = [[i * 6 + j for j in range(8)] for i in range(7)]
print(matrix)

[[0, 1, 2, 3, 4, 5, 6, 7], [6, 7, 8, 9, 10, 11, 12, 13], [12, 13, 14, 15, 16, 17, 18, 19], [18, 19, 20, 21, 22, 23, 24, 25], [24, 25, 26, 27, 28, 29, 30, 31], [30, 31, 32, 33, 34, 35, 36, 37], [36, 37, 38, 39, 40, 41, 42, 43]]


In [271]:
import numpy
matrix = numpy.arange(56).reshape(7, 8)
print(matrix)

[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23]
 [24 25 26 27 28 29 30 31]
 [32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47]
 [48 49 50 51 52 53 54 55]]


**=====================================**

In [283]:
key = ['a', 'b']
subk = [1, 2, 3]
dict1 = {k: {sk: k for sk in subk}for k in key}
print(dict1)

{'a': {1: 'a', 2: 'a', 3: 'a'}, 'b': {1: 'b', 2: 'b', 3: 'b'}}


### <u>2.11 Форматированный вывод строк</u>

In [315]:
rank = 'grajdanskyj'
name = 'snejok'
print(f'{name=:^8}, {rank=:^16}')

name= snejok , rank=  grajdanskyj   


In [327]:
print('name=%8s, rank=%14s' % (name, rank))

name=  snejok, rank=   grajdanskyj


In [329]:
print('name={:^8}, age={:^16}'.format(name, rank))

name= snejok , age=  grajdanskyj   


**=====================================**

In [342]:
x = 3
y = 4
print(f'{x**y =:.2f}, {(x * y)=:03d}')

x**y =81.00, (x * y)=012


In [350]:
print('x**y=%.2f, x + y=%02d' % (x**y, x + y))

x**y=81.00, x + y=07


In [352]:
print('x**y={:.2f}, x + y={:02d}'.format(x**y, x + y))

x**y=81.00, x + y=07


### <u>2.12 Файловый объект
</u>

In [360]:
'''file = open('tmp.txt')
file.readline()
file.close()'''

"file = open('tmp.txt')\nfile.readline()\nfile.close()"

In [358]:
'''file = open('tmp.txt','a') 
file.write(str(100) + '\n')
file.close()
file = open('tmp.txt')
print(file.read())
file.close()'''

"file = open('tmp.txt','a') \nfile.write(str(100) + '\n')\nfile.close()\nfile = open('tmp.txt')\nprint(file.read())\nfile.close()"

In [362]:
'''file = open('tmp.txt','a') 
file.writelines(['200 \n', '300 \n'])
file.close()
file = open('tmp.txt','r')
print(file.read())
file.close()
'''

"file = open('tmp.txt','a') # открыть для дозаписи в конец файла\nfile.writelines(['200 \n', '300 \n'])\nfile.close()\nfile = open('tmp.txt','r')\nprint(file.read())\nfile.close()\n"

## Задание 2.3

1) строка имеет длину 6, а при вызове str1[10]
запрашивается 11й элемент последовательности.
2) В Python оператор + для списков предназначен только для конкатенации списков с другими списками.
3) Индексация по несуществующему ключу словаря приводит к ошибке.
4) Кортежи в Python неизменяемы.
5) списки не могут быть элементами множеств или ключами словарей, так как они изменяемы. + 4й пункт.
6) Индексация словаря по несуществующему ключу является ошибкой.
7) Операция index будет работать только тогда, когда заданная подстрока существует.
8) Была вызвана незаданная (несуществующая переменная)
9) abs стал числом, а не функцией

## Задание 3
